server:
  port: 8081
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

#开发配置
spring:
  #profiles: dev
  #debug: true
  application:
    name: jhoper-user
  datasource:
    url: jdbc:mysql://localhost:3306/hoper?serverTimezone=GMT%2B8
    username: root
    password: lby604
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
